capture = wlr
output_name = 1
# Use a non-standard port so it doesn't conflict with default Sunshine setups
port = 48010

resolutions = [
  1920x1080,
  2560x1440,
  3840x2160
]
fps = [60, 120]

stream_audio = disabled
