[[language]]
name = "rust"
auto-format = true

[language-server.rust-analyzer.config.check]
command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "sql"
auto-format = true
